//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Educational_details
    {
        public string Id { get; set; }
        public Nullable<int> tenth_pass_year { get; set; }
        public Nullable<int> tenth_marks { get; set; }
        public Nullable<int> twelfth_pass_year { get; set; }
        public Nullable<int> twelfth_marks { get; set; }
        public Nullable<int> Grad_pass_year { get; set; }
        public string course_grad { get; set; }
        public Nullable<int> Grad_marks { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
