//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_details
    {
        public string Id { get; set; }
        public string Mother_Name { get; set; }
        public string Father_Name { get; set; }
        public string E_mail { get; set; }
        public Nullable<int> Phone_Number { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Designation { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
