//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class intern_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public intern_details()
        {
            this.intern_login = new HashSet<intern_login>();
        }
    
        public string intern_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> e_dob { get; set; }
        public string gender { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<int> phone_no { get; set; }
        public Nullable<int> highschool_per { get; set; }
        public Nullable<int> graduation_per { get; set; }
        public Nullable<int> intermediate_per { get; set; }
        public Nullable<int> aadhar_no { get; set; }
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<intern_login> intern_login { get; set; }
    }
}
