//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberWeek2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string fname { get; set; }
        public string mname { get; set; }
        public string lname { get; set; }
        public Nullable<int> num { get; set; }
        public int eid { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string address { get; set; }
    }
}
