//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL
    {
        public string PanCardNumber { get; set; }
        public string ResidentialAddress { get; set; }
        public string EmailId { get; set; }
        public string GithubUsername { get; set; }
        public string LinkedInProfile { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<int> EmploymentId { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
