//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Password { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
