//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesEducationQualification
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> EducationQualificationId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string University { get; set; }
        public Nullable<double> Marks { get; set; }
    
        public virtual EducationQualification EducationQualification { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
