//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int CygId { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Designation { get; set; }
        public string Email_Id { get; set; }
        public string Phone_No_ { get; set; }
    }
}
