//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newpr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pinfo
    {
        public string Name { get; set; }
        public string Fathersname { get; set; }
        public string Eid { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Designation { get; set; }
        public string Supervisor { get; set; }
        public string Gender { get; set; }
        public string Emailid { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
