//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberWeek2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CyberEmployee
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string E_mail { get; set; }
        public string Qualification { get; set; }
        public string Project { get; set; }
        public string Designation { get; set; }
    }
}
