//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cygrp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usernames
    {
        public string Username1 { get; set; }
        public string Email_ID { get; set; }
        public string Password { get; set; }
    }
}
