//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignUp
    {
        public string FName { get; set; }
        public string LName { get; set; }
        public int ID { get; set; }
        public string EmailID { get; set; }
        public Nullable<long> Number { get; set; }
        public string Password { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
