//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeProjct.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeData
    {
        public Nullable<int> Id { get; set; }
        public string IdType { get; set; }
        public string IdNumber { get; set; }
        public string MartialStatus { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Home { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string State { get; set; }
    
        public virtual SignUp SignUp { get; set; }
    }
}
