//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenticateUser
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
        public Nullable<bool> Terms { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
