//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationDetail
    {
        public string Id { get; set; }
        public string TenthBoard { get; set; }
        public Nullable<double> Tenthmarks { get; set; }
        public string Twelfthboard { get; set; }
        public Nullable<double> Twelfthmarks { get; set; }
        public string GraduationDegree { get; set; }
        public Nullable<double> GraduationMarks { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
